### ISSUE TITLE
Lift 16 Thread limit for Ryzen and future Processors

### ISSUE THREAD

**Issue by dangi12012** [niklasf/stockfish.wasm#26]
The 1gb and 16 thread limit is really bad compared to native stockfish-avx performance. 
On Ryzen and future intel processors (anything above 8 cores) you lose speed.

So i would suggest setting threadpool size up to 64 threads. (This will yield +100% nps)
I dont know if 1GB is a hard limit but i would suggest 4GB. (This probably will yield +5%)

stockfish.wasm is currently limiting analysis performance on lichess.org.

**Comment by niklasf** [comment]
Unfortunately browsers aren't quite ready for this, with restrictions on the number of web workers for threads and allocated memory. (And it does make some sense that vendors are careful, not allowing random websites to allocate 4GB of RAM and run extremely CPU intensive tasks.) Will raise the limits, when it becomes possible in mainstream browsers.

A browser extension to make native Stockfish available might be a good approach, though: https://github.com/ornicar/lila/issues/7909

**Comment by dangi12012** [comment]
Well some browsers for sure arent but you could always check if you are running chrome 80+ no?
Chromium has no thread limit as far as i am aware of. No such mention in the [Documentation](https://chromium.googlesource.com/chromium/src/+/master/docs/threading_and_tasks.md)

**Comment by niklasf** [comment]
Ok, I guess we can consider it a bit more carefully.

Is there a way to feature test that, rather than checking browser versions? What's `navigator.hardwareConcurrency` for you in Firefox and Chrome?

The memory limit is harder. 4 GiB is the maximum for wasm32, but we can't use *all* memory for hashtables. So 2 GiB would be the only feasible power of two. But even for that, it's not clear, that there will always be I continguous slice of 2 GiB available, especially when resizing the hashtable. `navigator.deviceMemory` for feature detection is only available in Chrome, and it goes to a maximum of 8 GiB, which is not a lot of margin for other stuff on the system (including perhaps even a second multi-variant instance, as used on Lichess when switching between study chapters).

**Comment by niklasf** [comment]
Oh, also let's not forget about the memory overhead of threads. Extrapolating https://github.com/niklasf/stockfish.wasm/issues/4#issuecomment-546603974, we'd need more than 1 GiB of memory for threads alone. A mitigating factor is that someone with 64 threads will very likely also have a bit of RAM to go with it.

**Comment by dangi12012** [comment]
Memory is not the issue. Going in hashtable size from 1 to 4GiB does not yield great increase so 1gb is ok i think. (only few percentage after 256mb in my experience)
Keep in mind Firefox has 3.77% market share and is declining - and Microsoft just switched to Chromium. 

**AMD Ryzen 9 5950X**
[Chrome] navigator.hardwareConcurrency = 32
[Firefox] navigator.hardwareConcurrency = 16

**AMD Ryzen 9 3900X**
[Chrome] navigator.hardwareConcurrency = 24
[Firefox] navigator.hardwareConcurrency = 16

These are half of the cores and running two threads per core is usually 5% faster for AVX and 15% faster for non AVX versions (less alu unit idling). I think you could savely allow 64 Threads or up to 2 * hardwareConcurrency for stockfish.wasm

**Comment by niklasf** [comment]
Oh, that's great! I was expecting Firefox to give 32 or 64, and then fail when allocating more than 20.

**Comment by niklasf** [comment]
Increase to 32 published as v0.9.1, and deployed to the Lichess testing site https://lichess.dev/analysis. Can you please confirm that it works in Chrome and Firefox?
